---
- hosts: all

  tasks:
    - name: Run a command
      shell: echo Hello Word
      register: runout

    - name: Print some info
      debug:
        var: runout
      when: "'World' not in runout.stdout"

    - name: Print out if Disk exists
      debug:
        msg: "Storage exists"
      when: ansible_devices['sdx'] is not defined